### ISSUE TITLE
isValid always return true

### ISSUE THREAD

**Issue by robertnicjoo** [brockpetrie/vue-moment#104]
I am trying to show different data when data from my database is valid or not but it always return true.

`example`

```
Today: 2018-09-12
if my database column is set to:
2018-09-11 (valid)
2018-09-15 (valid)
2018-09-01 (valid)
2018-08-11 (valid)
```

Here is my code:

```html
<template v-if="`${project.deadline | formatExpire}`">
data when date is valid
</template>
<template v-else>
data when date is NOT valid
</template>
```

```javascript
import moment from 'moment';
moment.locale('id');
import timeZone from 'moment-timezone';
export default {
//data part etc.
  filters: {
    formatExpire: function(value){
                return moment(value, "YYYY-MM-DD").isValid();
    },
  }
}
```
# Logic

If today is SAME or BEFORE database date return `v-if` part, otherwise return `v-else` part.

any idea how can i check that date of mine?

**Comment by BrockReece** [comment]
Personally, I wouldn't use a filter for this (I'm not even sure if you can) as filters are designed for manipulating and displaying data. I would create a method and point the `v-if` at that.

And for the logic, I would use moment's `isSameOrBefore` function that would seem to fit your use case perfectly.

```html
<div v-if="sameOrBefore(date)">
  data when date is valid
</div>
<div v-else>
  data when date is NOT valid
 </div>
```

```js
methods: {
  sameOrBefore(date) {
    return date.isSameOrBefore(this.$moment(), 'd')
  }
}
```

https://codesandbox.io/s/r5m031kjop

Does that make sense?

**Comment by robertnicjoo** [comment]
@BrockReece  that's not working for me :/ returned result is same as i explained in my question.

I also made some changes in my code, here is my latest codes:

```javascript
formatExpire: function(value){
                return moment(value, "YYYY-MM-DD") >= moment().format("YYYY-MM-DD")
            },
```
```html
<template v-if="`${project.deadline | formatExpire}` !== 'false'">
        data when date is valid
</template>
<template v-else>
          data when date is NOT valid
</template>
```

still same issue (shows `v-if` part in all conditions)

**Comment by BrockReece** [comment]
Which part of my suggestion isn't working? Do you have any error's in the console? Have you tried adding some debugging to your `formatExpire` method to see what that is actually returning?

Did you look at the code sandbox example I sent? Unless I have misunderstood your requirements, this demonstrates a combination of v-if and a method that determines whether a date is in the past or not and ultimately shows different content.

**Comment by robertnicjoo** [comment]
> Which part of my suggestion isn't working?


As I said isn't working = return `true` always.

>  Do you have any error's in the console?

@BrockReece  as i'm working with vue in laravel i had to change some part of your code (nothing important) just like changing `$moment` to `moment` and so... finally i got the results without error.

> Have you tried adding some debugging to your formatExpire method to see what that is actually returning?

Infact I did. I tried to make JS custom function and I realized that I have issue getting `deadline` value in my script`

# Code

So I've made a method like:

```javascript
mounted: function() {
            this.formatExpire();
},
methods: {
            formatExpire(){
                let value = this.project.deadline;
                let test = moment(value).format("YYYY-MM-DD");
                let currentday = moment().format("YYYY-MM-DD");
                if(test >= currentday){
                    console.log("dead " +test+ " is bigger or equal to " +currentday+" valid");
                    console.log(value);
                }else{
                    console.log("dead " +test+ " not bigger or equal to " +currentday+ " not valid");
                }
            },
}
```

and the results i got in console was:

```html
dead 2018-09-13 is bigger or equal to 2018-09-13 valid //return by console.log("dead " +test+ " is bigger or equal to " +currentday+" valid");
undefined  //return by  console.log(value);
```

So As you see in my `test var` i'm getting date of today instead of `deadline` column from database.
And in my `value` I get `undefined`.
So I think the only reason that I get date of today is because `moment.js` replace `undefined` with today by `.format()` part.

**Comment by robertnicjoo** [comment]
Last changes:

```javascript
formatExpire(value){
                // let test =  moment(value).format("YYYY-MM-DD") >= moment().format("YYYY-MM-DD");
                // console.log("testing "+test+ "");
                return moment(value).format("YYYY-MM-DD") >= moment().format("YYYY-MM-DD");
            },
```
```html
<template v-if="`${formatExpire(project.deadline)}` != 'false'">
show valid
</template>
<template v-else>
show Not valid
</template>
```

**Comment by BrockReece** [comment]
Sorry my reference to `$moment` was assuming you are using this repo's plugin `vue-moment` and not just using `moment in vue`.

Glad you have something working though.
