### ISSUE TITLE
add {{variable}} to dates

### ISSUE THREAD

**Issue by kevinstory** [brockpetrie/vue-moment#107]
I'm trying to do a v-for loop to list out some dates but I cannot figure out how to use the momentjs add function with a variable. 
Example:
{{ new Date() | moment("add", "1 days", "MMM Do YY") }}

How can I make the "1" a variable number?

**Comment by BrockReece** [comment]
You can use the [Template Literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) when building the arguments for the moment filter. Something like this will work.

```html
{{ date | moment("add", `${i} days`, "MMM Do YY") }}
```

I have posted a working example [here](https://codesandbox.io/s/n4zqx8n9mm)
