### ISSUE TITLE
Exclude Locales in Nuxt

### ISSUE THREAD

**Issue by Jesus82** [brockpetrie/vue-moment#115]
Hi, I'm using this module with nuxt.js I import it to the component where I want to use it with 
```
import Vue from 'vue';
import VueMoment from 'vue-moment';
Vue.use(VueMoment);
```
My question is if there is any way to exclude all the locales but English.
Thanks in advance!

**Comment by Teranode** [comment]
install `@nuxtjs/moment` https://www.npmjs.com/package/@nuxtjs/moment
