### ISSUE TITLE
Different behavior of vue-moment compared to vanilla

### ISSUE THREAD

**Issue by Scarwolf** [brockpetrie/vue-moment#119]
Hey there.

I found a snippet on Stackoverflow to convert Seconds to HH:mm:ss. For example, 90 Seconds should return 00:01:30.

Now, this is the snippet in vanilla:

```javascript
// Vanilla Moment.js
let secs = 90;
let formatted = moment.utc(secs * 1000).format("HH:mm:ss");
// Returns 00:01:30
```

Then I changed this to the vue-moment syntax:
```javascript
// Vue-Moment
let secs = 90;
this.$moment().utc(secs * 1000).format("HH:mm:ss")
// Returns 10:51:17
```

As you can see, vue moment takes the current time, whilst vanilla starts at midnight.

To avhieve the same using vue-moment I need to do this:

```javascript
let secs = 90;
this.$moment().startOf('day').seconds(secs).format('HH:mm:ss')
```

Is this expected behaviour or am I missing out on something obvious? vue-moment has just been installed with no extra configuration.

**Comment by BrockReece** [comment]
Hey, what happens if you try `this.$moment`, as opposed to `this.$moment()`
```js
this.$moment.utc(secs * 1000).format("HH:mm:ss")
```

**Comment by naaando** [comment]
I'm having the same problem, using `this.$moment` works here.

**Comment by Scarwolf** [comment]
Whoops, sorry for the late answer. Thanks to @BrockReece, your code works fine. Odd, but it works. Thanks!
