### ISSUE TITLE
Getting unrecognized time in 24hr format.

### ISSUE THREAD

**Issue by VinceSanityyy** [brockpetrie/vue-moment#137]
I got a time format like this from my database `12:30:00` and `14:30:00`. But when i want to display it in my component like this
```
<li class="list-group-item">
<b>Time</b> <a class="pull-right">
{{schedule.start_time | moment('hh:m a')}} - {{schedule.end_time | moment('hh:m a')}}</a>
</li>
```
It doesnt work and i got a warning 
`app.js:118394 Could not build a valid `moment` object from input.`

In my backend, I save time in this format
```
$from = date('H:i:s',strtotime($request->start_time));
$to = date('H:i:s',strtotime($request->end_time));
```

Can someone tell me what is the problem of this?

**Comment by BrockReece** [comment]
So you are trying to build a moment instance just with the time and no date?

**Comment by VinceSanityyy** [comment]
Yes thats what i want @BrockReece

**Comment by BrockReece** [comment]
I don't think moment can handle "time of day" as an input. 
I think you would have to trick moment, by prepending the time with an arbitrary date.

The following worked for me in the template

```vue
{{ `${$moment().format('YYYY-MM-DD')} ${schedule.start_time}` |  moment('hh:m a') }}
```

but if you want to clean this up a bit, you could create your own [filter](https://vuejs.org/v2/guide/filters.html) to build a valid moment input and chain that with the moment filter

```vue
<template>
  <div>
    {{ schedule.start_time | timeOfDay |  moment('hh:m a') }}
  </div>
</template>

<script>
export default {
  filters: {
    timeOfDay(time) {
      const date = "1970-01-01";
      return `${date} ${time}`;
    }
  },
}
</script>

```
I hope that helps.

**Comment by VinceSanityyy** [comment]
Okay will try that sir @BrockReece . I will update the issue once im done implementing it. Thanks a lot.

**Comment by VinceSanityyy** [comment]
Thanks @BrockReece
