### ISSUE TITLE
moment-timezone does not work for tz Pacific/Auckland with vue-moment

### ISSUE THREAD

**Issue by KiwiChris-xx** [brockpetrie/vue-moment#145]
Hi, I am unable to get time zone Pacific/Auckland to work other tz do work ok with the same implementation.

Has anyone come across this issue before?
Can you replicate this issue?

Is there something I am doing wrong?

implementation
```
import VueMoment from 'vue-moment'
import moment from 'moment-timezone'

"moment-timezone": "^0.5.31",
"vue-moment": "^4.1.0",
"vue": "^2.6.11",

moment.tz.setDefault('Pacific/Auckland') 
Vue.use(VueMoment, {
  moment,
})

<template>
<div>
{{ timestamp | moment("ddd, MMM D YYYY hh:mm")}}
</div>
</template>
```

input unix timestamp example: 1595991878
expected result to be: 15:04 got: 03:04 UTC: 03:04:38

When changing tz to others correct result is returned, tried:  America/New_York and Australia/Sydney with correct results

**Comment by BrockReece** [comment]
Is the problem with your time formating?
I believe `hh:mm` is  for a 12 hour format. 
Try `HH:mm`?

**Comment by KiwiChris-xx** [comment]
@BrockReece you are totally correct, user error after all.

Thank you so much you saved my bacon.
