### ISSUE TITLE
Compatibility issues with vue 3

### ISSUE THREAD

**Issue by larsrbak** [brockpetrie/vue-moment#148]
The vue 3 use method assumes an installer that takes a vue instance rather that the static vue reference. Example of desired usage:

```
import { createApp } from "vue";
import App from "./App.vue";
import VueMoment from 'vue-moment';

createApp(App)
  .use(VueMoment)
  .mount("#app");
```

Does anyone know a quick workaround and where vue 3 support in the pipeline?

**Comment by BrockReece** [comment]
I don't think you can use filters in Vue 3, so I think we will need to rethink how this lib is going to work going forward.

**Comment by larsrbak** [comment]
You are right. Filters are not a thing in vue 3. They suggest using computed values or methods. I will just close this issue.
