### ISSUE TITLE
Example for using within string interpolation in Vue template

### ISSUE THREAD

**Issue by ux-engineer** [brockpetrie/vue-moment#149]
This works in template: `{{ item.date | moment('LL') }}`

However, when I'm needing to add an optional string segment after the previous code with additional text content, I'm finding that string interpolation within template syntax doesn't seem to find moment instance in it's execution scope...

```
{{ item.read ? ` (read at ${item.read | moment('LL')})` : '' }}
```

Or:

```
{{ item.read ? ` (read at ${moment(item.read, 'LL')})` : '' }}
```

Tried a few variations. Is there a way to get it work with some alternative syntax without needing to explicitly add moment instance into the component scope?

**Comment by ux-engineer** [comment]
Found an alternative way: `<small v-if="item.date">{{ item.date | moment('LL') }}<span v-if="item.read"> (read at {{ item.read | moment('LL') }})</span></small>`

Yet this question / issue may come up with other people later, so it might be good to have an answer for. But Vue 3 changes syntax really soon...

**Comment by BrockReece** [comment]
I would usually handle it the way that you have. Or within a computed property.

```js
readAt() {
  return this.item.read  ? `read at ${this.$moment(this.item.read).format('LL')}` : ''
}
```

As for the comment on Vue 3 changes. Filters are being removed and this whole lib is based around filters so there are going to have to be fundamental changes.
