### ISSUE TITLE
How do I change the language to Spanish ?

### ISSUE THREAD

**Issue by edandy** [brockpetrie/vue-moment#15]
How do I change the language to Spanish ?

**Comment by BrockReece** [comment]
Hi @edandy 

I put an option in a while back to pass through a custom moment object when installing the plugin, so you should be able to set the language in the same way as if you were using moment.js and pass this through to vue-moment 

```js
const moment = require('moment')
require('moment/locale/es')
    
Vue.use(require('vue-moment'), {
    moment
})

console.log(Vue.moment().locale()) //es
```

I hope this helps?
Brock

**Comment by Ovilia** [comment]
@BrockReece It would be better if you tell provide this information in README.md. :)
Nice library! Thanks!

**Comment by BrockReece** [comment]
@Ovilia. Thanks, It isn't my library though, just helping out :) I will make a PR for the readme when I get some time.
