### ISSUE TITLE
moment from, update automatic

### ISSUE THREAD

**Issue by Robertbaelde** [brockpetrie/vue-moment#17]
Hi, 

First of all, great package. 

Is it possible to update all filters every minute. now the from now filter will stay on the time it's calculated. It would be great if those would update when a minute has passed. so a minute ago would turn into two minutes ago etc..

**Comment by shakee93** [comment]
@Robertbaelde this package just contains the filters. you can setup a data object which updates the date in real time. and use this to show it formatted.

```
data : {
      realTime // update this variable to real time using setTimeout or something
}
```
and use it just like before

```
<p> {{ realTime | moment }} </p>
```

w3schools example here http://www.w3schools.com/js/tryit.asp?filename=tryjs_timing_clock
