### ISSUE TITLE
how to handle UTC ? equivalent for moment.utc(String).format() ?

### ISSUE THREAD

**Issue by darkylmnx** [brockpetrie/vue-moment#18]
Is there any way to acheive UTC, converting to UTC must work with the "chaining" but converting from UTC to LOCALE won't work with what you have actually

**Comment by Voziv** [comment]
+1 here, trying to figure out how to do UTC to local

**Comment by brockpetrie** [comment]
I agree this would be nice to have. Filing this for consideration in the next release.

**Comment by tuliosciotta** [comment]
+1

**Comment by brockpetrie** [comment]
Fixed in #62, will close this when #61 is merged.

**Comment by madebysoren** [comment]
What is the status on this one? And how is it going to be used?

Like this?

> <span>{{ item.published_on | moment("utc") | moment("from") }}</span>

**Comment by iamstevendao** [comment]
+1
