### ISSUE TITLE
publish on npm?

### ISSUE THREAD

**Issue by laander** [brockpetrie/vue-moment#2]
Neat little collection of filters. You should publish them on npm for easy install :+1:

**Comment by joshuajohnson814** [comment]
^ what he said :)

**Comment by brockpetrie** [comment]
Done. Thanks to @BrockReece for doing this.

**Comment by pepf** [comment]
Hi, Just a suggestion,
When using npm and _import_ syntax rather than require, this would be a way to make it work:

```js
import VueMoment from 'vue-moment'
Vue.use(VueMoment)
```

Maybe add to the readme document?
