### ISSUE TITLE
Moment parse string to date with format

### ISSUE THREAD

**Issue by yang5664** [brockpetrie/vue-moment#22]
in file vue-moment.js should be like this....
```ruby
// add "format" option
Vue.moment = function(data, format) {
	return moment(data, format);
}
```
refs from http://momentjs.com/docs/#/parsing/string-format/

**Comment by Eden-Sun** [comment]
Since there might me more than 2 arguments, spreading would be a better.
Or maybe just  
`Vue.moment = moment` ?

**Comment by yang5664** [comment]
Sorry, What if I need use Moment format like this, How to make it?
```ruby
Vue.moment("OD20161226153059001".substr(2,14), "YYYYMMDDHHmmss").format("YYYY / MM / DD HH:mm")
```

**Comment by Eden-Sun** [comment]
@yang5664 
for cases more than one argument, just dont use `Vue.moment` function
uses
```js
import moment from 'moment'
...
moment("OD20161226153059001".substr(2,14), "YYYYMMDDHHmmss").format("YYYY / MM / DD HH:mm")
```

**Comment by yang5664** [comment]
Thank you so much.
