### ISSUE TITLE
Vue 2.0 compatibility

### ISSUE THREAD

**Issue by ibarral** [brockpetrie/vue-moment#23]
Is vue-moment compatible with Vue 2.0+? I can't make it work.
Thanks!

**Comment by inhuman-programmer** [comment]
@ibarral it is compatible, but instead of
`{{ now | moment "hh:mm:ss" }}`
use
`{{ now | moment("hh:mm:ss") }}`

**Comment by melanke** [comment]
this should be in the README.md

**Comment by SiamKreative** [comment]
How about this in vue 2+ please?
`<span>{{ [ someDate, "MM.DD.YY" ] | moment "dddd, MMMM Do YYYY" }}</span>`

**Comment by kartsims** [comment]
Didn't work for me using vue 2.1.0

Got this error : 
```
+-- UNMET PEER DEPENDENCY vue@>=1.x.x
`-- vue-moment@2.0.2 
  `-- moment@2.17.1 

(...)

npm WARN vue-moment@2.0.2 requires a peer of vue@>=1.x.x but none was installed.
```

**Comment by aslak01** [comment]
@SiamKreative just put it in a parenthesis and remove spaces like foreggs demonstrated. 
<span>{{ [ someDate, "MM.DD.YY" ] | moment("dddd, MMMM Do YYYY") }}</span>

I agree with melanke that the readme should be updated.

**Comment by briangonzalez** [comment]
This is now in the readme via https://github.com/brockpetrie/vue-moment/pull/28

I propose we close this.

**Comment by Christilut** [comment]
this isnt reflected in the npmjs documentation yet
