### ISSUE TITLE
[feature request] Allow time comparison as conditional

### ISSUE THREAD

**Issue by InstanceOfMichael** [brockpetrie/vue-moment#24]
```
<div v-if="moment().isBefore(otherTime)"></div><div v-else></div>
```

It would be awesome if we had something for this, except at the moment of inflection (when `moment().isBefore(otherTime)`'s status changes from `true` to `false`) Vue is able to detect it as a change and react accordingly.

Here is a similar discussion, but did not provide a clean API for accomplishing this. https://github.com/vuejs/Discussion/issues/214

**Comment by brockpetrie** [comment]
I think this is a really cool idea that's a bit outside this library's scope, as this is focused principally on manipulating and displaying dates rather than querying them.

Good food for thought though! You've got me thinking of elegant ways to solve this.
