### ISSUE TITLE
Feature request: when given empty string it should output an error message that is customizable. 

### ISSUE THREAD

**Issue by thegreyfellow** [brockpetrie/vue-moment#29]
Hi there, first thanks for this library it works like a charm !! I just love using it instead of directly hooking momentJS to the project. the only drawback I can see is that when given an empty string as the date to filter it outputs the date of today and there is no way to check on a data if it's empty or not before filtering it in vueJS. 

So my proposition is adding a *methods* mixin so we can use the `moment()` as a function if filters are not the solution the situation.

And thanks for your time.

**Comment by brockpetrie** [comment]
I think this is a smart idea. I feel like this is an instance where moment shouldn't try to assume the nature of the input. If someone wants to filter the current date, they should pass in `Date.now()` or a variable representing it. If the date input is null, the filter should fail, or at least log a warning in console.

**Comment by qhbhq** [comment]
I also want this feature. When given empty string, it should return empty string , not default date

**Comment by BrockReece** [comment]
This shouldn't be too hard to implement.
Do you want me to have a look at it?

**Comment by brockpetrie** [comment]
@BrockReece that'd be great!

**Comment by BrockReece** [comment]
@brockpetrie I have expanded the logic below to include a check for an undefined input, should I also be checking for an empty string?
```js
// before
if (!date.isValid()) {
// after
if (typeof input === 'undefined' || !date.isValid()) {
```
I have also added some test coverage as to what inputs are handled correctly and caught by this check. I will have a PR to you by the morning.

**Comment by brockpetrie** [comment]
@BrockReece I think we can just check if input is falsey, which should catch all of the problematic inputs we're trying to check for.
```js
if (!input || !date.isValid()) {
```

**Comment by brockpetrie** [comment]
v3.0.0 via #53 now uses this behavior. Thanks @BrockReece for the fix and @thegreyfellow for the suggestion!
