### ISSUE TITLE
Feature Request: Moment.duration

### ISSUE THREAD

**Issue by ralphchristianeclipse** [brockpetrie/vue-moment#30]
This solves cannot create moment object when passing only a time string

**Comment by jezmck** [comment]
Agreed, we need to be able to use `moment`'s [Duration](https://momentjs.com/docs/#/durations/) feature.

**Comment by Spoowy** [comment]
Yep!

**Comment by BrockReece** [comment]
Would this be solved by #37 or have I misunderstood?

**Comment by brockpetrie** [comment]
This will be added in #61, so will be closing this when that's merged.
