### ISSUE TITLE
Tiemzone Support

### ISSUE THREAD

**Issue by tmorehouse** [brockpetrie/vue-moment#31]
Does `vue-moment` support moment timezone?

**Comment by evertramos** [comment]
Yes it does. 

Visit: http://momentjs.com/ and see what fits to you. 

And here is where you can set it up using vue-moment:

https://github.com/brockpetrie/vue-moment#configuration

**Comment by tmorehouse** [comment]
Perfect!

Thanks!

**Comment by evertramos** [comment]
Just one more comment @tmorehouse, since this repo has not been updated for a while, not sure if it´s under development, so, you might want to use just regular moments lib, directly to vue, as of below:

In your requires file, just use:
```
window.moment = require('moment');
window.moment.locale('pt-br');
```

and then use wherever you want as of:
```
window.moment(this.date)format('DD-MMMM');
```

Hope it helps!
