### ISSUE TITLE
UNIX Timestamp

### ISSUE THREAD

**Issue by sebastianks** [brockpetrie/vue-moment#33]
I can't find a way to make it work with UNIX timestamps. Is it possible or did you cut off this feature?

Moment.js states you can do `moment.unix(value).format("MM/DD/YYYY")` but how can I do this with your filter?

**Comment by sebastianks** [comment]
If anyone has the same issue, then you can use this function in your `methods` property of your Vue component. This will format your unix timestamp to a valid date that Moment can use.

`
formatDate(unix) {
				const date = new Date(unix * 1000); // convert to milliseconds
				const year = date.getFullYear();
				let month = date.getMonth() + 1;
				let day = date.getDate();

				// Check if day or month is only 1 digit
				// this because Moment.js works with 0 leading values
				if (day.toString().length !== 2) day = `0${day}`;
				if (month.toString().length !== 2) month = `0${month}`;

				return `${year}-${month}-${day}`;
},
`

**Comment by mcescalante** [comment]
I just ran into this same issue and did some digging. `moment` itself as a library supports unix timestamps with `moment.unix()`. I installed moment, imported it, and added a filter into my component to do Unix timestamps for me:

```vue
 filters: {
    formatDate: function (value) {
      if (value) {
        return moment.unix(value).format('MM-DD-YYYY')
      }
    }
  },

```

This will take Unix epoch (timestamp) as input and give you back `MM-DD-YYYY`. I prefer filters to methods.

**Comment by Joeper214** [comment]
I install vue-moment in my vue appliction and created the filter but this returns:

```javascript
[Vue warn]: Error in render function: "ReferenceError: moment is not defined"

found in

---> <App> at src/components/App.vue
       <Root>
```

**Comment by savagemechanic** [comment]
@Joeper214 install moment for the filter not vue-moment. npm install --save moment

**Comment by brockpetrie** [comment]
Unix epoch support added in #58— will close this when it's merged in.
