### ISSUE TITLE
Support options on calendar

### ISSUE THREAD

**Issue by gil0mendes** [brockpetrie/vue-moment#38]
Hello,

The latest versions of moment support an options parameter when calling calendar, would be nice if vue-moment support it 😉

## Syntax example

```html
<span>{{ new Date() | moment("calendar", null, { sameDay: '[Today]' }) }}</span>
<!-- e.g. "Today" -->
```

**Comment by brockpetrie** [comment]
Added in #60, will close this when #61 is merged.
