### ISSUE TITLE
moment is not defined

### ISSUE THREAD

**Issue by tanhs** [brockpetrie/vue-moment#41]
I am getting the error above.

I have done the following 
1. npm install moment 
2. In the app.js file, I have tried both of the following:

```
import moment from vue-moment;
Vue.use(moment);
```

3. npm run dev
4. do a console.log(moment());
5. got error: moment is not defined in the debug console

**Comment by BrockReece** [comment]
What where you expecting `console.log(moment());` to do? Were you expecting it to output a moment object? If so, I think you have misunderstood what is going on here.

`import moment from vue-moment;` will import the vue-moment plugin, which is a js module. The plugin will add a proxy to moment that you can access from within your app.js like so...

```js
console.log(Vue.moment())
```

It also allows you to access it from within a vue component, like this...
```js
console.log(this.$moment())
```

I hope this helps?

**Comment by tanhs** [comment]
Thank you.  Everything work fine with your feedback.
