### ISSUE TITLE
Humanize support function

### ISSUE THREAD

**Issue by JefferyHus** [brockpetrie/vue-moment#42]
Will there be any implementation for `moment.duration().humanize();` function?

**Comment by BrockReece** [comment]
How did you imagine this working?
I could see there may be a need for another filter for moment durations and I guess it would be an option in that?

**Comment by brockpetrie** [comment]
Hmm, not too sure about this. I feel like duration is so little used, and I think one can basically do a workaround using `from` anyway.

**Comment by JefferyHus** [comment]
I have done a workaround, and it's been approx 1 month :p, thanks for the replies, just to add even if things seems to be non-convenient you may integrate it, because a solution is here to help and save time for people :+1: . In the end thanks for the replies and wish you the best.
