### ISSUE TITLE
Moment time zone

### ISSUE THREAD

**Issue by hkmsadek** [brockpetrie/vue-moment#43]
How to parse time correctly according to time zone of users

**Comment by ognyandim** [comment]
I am experiencing the same - 
`someDate| moment('DD-MM-YYYY')`
does not respect the currently set time zone. In my case the time zone in the app screen is different from the time zone on the computer.

**Comment by BrockReece** [comment]
How are you setting the timezone in your app?
what does this command print out? And was it what you were expecting?
```js
this.$moment().utcOffset()
```

**Comment by ognyandim** [comment]
We use [moment-timezone](https://momentjs.com/timezone/) and set it like this : 

`moment.tz.setDefault(timeZoneIANAId);`

**Comment by BrockReece** [comment]
What happens if you set the timezone through $moment
```js
this.$moment().tz.setDefault(timeZoneIANAId)
```

**Comment by ognyandim** [comment]
tz is undefined in it even if it is imported in the current component.

**Comment by BrockReece** [comment]
Ok, how about passing your timezone ready moment instance into vue-moment?

```js
#main.js
import Vue from 'vue'
import VueMoment from 'vue-moment'
import moment from 'moment-timezone'

Vue.use(VueMoment, {
  moment,
})

...
```

**Comment by ognyandim** [comment]
I will skip it for now because I made a $formatDate(value, formatter) function in the root of  my components and internally I use moment too. In this way I do not need to import anything anywhere - only one line in my bootstrap : 

`Vue.prototype.$formatDate = formatDate;`

**Comment by BrockReece** [comment]
FYI, I have tested the code above and it works, I have also added a PR for adding a new `timezone` filter option to vue-moment, if that helps anyone at all.
```html
<div>{{ date | moment('timezone', 'America/Los_Angeles', 'LLLL ss')}}</div>
```

**Comment by brockpetrie** [comment]
Timezone convenience filters added in #51 courtesy of @BrockReece!
