### ISSUE TITLE
vue-moment throw error: Uncaught (in promise) TypeError: moment is not a function

### ISSUE THREAD

**Issue by AlfredMou** [brockpetrie/vue-moment#46]
I install vue-moment and throw error in  browser
![image](https://user-images.githubusercontent.com/9381681/31421060-dc4dc6f4-ae0a-11e7-8ce3-3f43cca8fc60.png)
I think it's because moment publish their new version 2.19.0,  moment export is changed to Object。

**Comment by BrockReece** [comment]
Thanks, I will have a look into this.

Which version of vue-moment are you using?

**Comment by BrockReece** [comment]
You are right, moment are having some other issues with v2.19.0 too. There is a PR (#45) to depend on v2.18.1, which I have just confirmed fixes this issue too. 

This will buy us some time to fix this properly.

**Comment by BrockReece** [comment]
I have tested this again this morning after the release of v2.19.1 and it seems to be working for me, can you confirm?

**Comment by AlfredMou** [comment]
@BrockReece  yes，this bug has been fixed  after the release of v2.19.1。thank you ！
