### ISSUE TITLE
template filter is not reactive

### ISSUE THREAD

**Issue by vwasteels** [brockpetrie/vue-moment#49]
Hello

I display a date like so :

```
{{ realTime | moment }}
```

And update it every second like this :

```
        data() {
            return {
                realTime: this.$moment()
            };
        },

        created() {
            setInterval((() => { 
                    this.realTime.add(1, 'second')
                    console.log(this.realTime.format());
                }).bind(this), 
                1000);
        }
```

the ```console.log```shows the updated value correctly, but the value displayed in the template remains the same...

Any idea ?

Thanks !

**Comment by vwasteels** [comment]
by the way, it works if I : 

```this.$forceUpdate();```

on the ```setInterval``` function

**Comment by BrockReece** [comment]
I'm guessing that this is to do with how Vue handles reactivity. I think Vue is not noticing the change to `realtime`.

Can you test this by trying this in your setInterval?
```js
this.realTime = this.$moment()
```

**Comment by vwasteels** [comment]
good call, it works that way...

too bad it has to initialize a new moment object each time, but at least it leaves reactivity to Vue core !

thanks !

**Comment by vwasteels** [comment]
In fact, what I needed is to switch to next/previous day, I ended up doing it like this : 

```
        data() {
            return {                
                date: this.$moment(),
            };
        },
        methods: {
            prev() { this.date = this.date.clone().subtract(1, 'day'); },
            next() { this.date = this.date.clone().add(1, 'day'); }
        }

```

**Comment by BrockReece** [comment]
cool, I'm pretty sure `clone` creates a new moment object under the hood, I think it basically is syntax sugar this...

```js
moment(this.date).add(1, 'day')
```

I am glad it is working for you though.
