### ISSUE TITLE
npm install vue-moment remove other vue add-in

### ISSUE THREAD

**Issue by tanhs** [brockpetrie/vue-moment#52]
why npm install vue-moment it removes other add-in such as vue-datetime.
what I have done is
1. npm install vue-datetime
2. npm install vue-moment
3. npm run dev --> prompt error vue-datetime not found, I check the directory is removed

**Comment by BrockReece** [comment]
Not sure, I will look into it this morning.

**Comment by BrockReece** [comment]
I'm afraid I can't replicate this. I have installed both **vue-datetime** and **vue-moment** on a fresh **vue-cli** project and I have both plugins working in my app.

What about if you use the `--save` flag on the npm install command?

**Comment by brockpetrie** [comment]
Not able to replicate this either. Closing
