### ISSUE TITLE
Filter for Converting Between Timezones

### ISSUE THREAD

**Issue by gbroques** [brockpetrie/vue-moment#55]
PR https://github.com/brockpetrie/vue-moment/pull/51 adds `moment-timezone` filters to `vue-moment`.

But I'm not sure how to convert from one timezone to another.

What I want to do is convert from UTC to America/Chicago like so:
```
moment.tz(date, 'UTC').clone().tz('America/Chicago');
```

I would imagine the API would be something like:
```
<span>{{ date | moment('timezone', 'UTC', 'clone', 'timezone', 'America/Chicago') }}</span>
```

Or the API could be smart and allow something like:
```
<span>{{ date | moment('timezone', 'UTC', 'America/Chicago') }}</span>
```

Maybe @BrockReece could answer the question of whether or not this is currently possible and provide a code snippet if it is?

**Comment by BrockReece** [comment]
Hi @gbroques 

We recently added a new `timezone` filter options in PR #51, though I have just realised that I didn't update the readme. Sorry about that. Your markup should look something like this...

```html
<span>{{ date | moment('timezone', 'America/Los_Angeles', 'LLLL ss')}}</span>
```

It's not doing anything special, it is just piping the second argument through `moment.tz()` and as such will not set the incoming moment object's timezone, you should handle that in your declaration of `date`.

```js
data() {
  return {
    date: moment.tz(date, 'UTC'),
  }
}
```

FYI, this filter essentially performs a clone on all moment objects passed through to it, so mutability shouldn't be of concern here either.

I hope that helps?

**Comment by gbroques** [comment]
@BrockReece Thank you! That helps. I didn't think to wrap the date before I passed it into the filter.

I can update the README for you?

**Comment by BrockReece** [comment]
@gbroques no problem.
Thanks, but I am already half way through writing the docs up, but maybe I could ask you to check them before I merge?

**Comment by gbroques** [comment]
Sure thing ;)

I'm closing this issue.
