### ISSUE TITLE
Unix timestamp in ms not working

### ISSUE THREAD

**Issue by donald-oelke** [brockpetrie/vue-moment#64]
After updating from 2.2.0 to the lastest version (3.1.0) it appears that the timestamp input must be provided in seconds, not milliseconds.  Many timestamps are given in ms, including the JS Date object.  I previously rolled back to 2.2.0 from a newer release because I thought it was a bug, but since it's still there I am wondering if the change was intentional.

Thanks for the help!

**Comment by brockpetrie** [comment]
This change was indeed intentional to accommodate Unix timestamps, which are in seconds rather than milliseconds. For anyone using milliseconds, you can get around this by just passing in `new Date(myMillisecondVar)`. Hope that helps!

**Comment by donald-oelke** [comment]
@brockpetrie thanks for clarifying.  Unfortunately that leaves the same problem as before the 3.0.0 fix for undefined inputs (since Date(undefined) == null, which will output "null" in the UI rather than an empty string).  The standard for moment.js is in ms which is one of the reasons we use it.  I wonder if there is a way to accept either input (I think moment(timestamp) might do this?).

**Comment by brockpetrie** [comment]
In that case, for dealing with undefined vars, you can always pass your input as `myMillisecondVar && new Date(myMillisecondVar)`, which will only pass in a parsed JS Date obj from your variable if it _isn't_ not undefined, null, etc.
