### ISSUE TITLE
Failed to resolve filter: moment

### ISSUE THREAD

**Issue by notflip** [brockpetrie/vue-moment#74]
I'm including moment as follows

    import * as moment from 'moment';
    Vue.use(moment);

But I'm getting the following error. Do I need to pass the moment instance somewhere in my components? Thank you

**Comment by notflip** [comment]
Including it using the example from the docs works.

**Comment by jonnyhoeven** [comment]
it does not. Vue.use(require('vue-moment')); is broken

**Comment by andreav** [comment]
same here,  vue-moment": ^4.0.0

**Comment by Alifar** [comment]
> Including it using the example from the docs works.

What docs are you referring to?

**Comment by BrockReece** [comment]
I have added a PR to change the docs to use `import` statements rather than the outdated `require`
Does this help?

**Comment by Alifar** [comment]
Well... it now kinda works... using:
`<div>{{ myDate | moment("from") }}</div>`

But it now breaks the translation, I had the translation setup like:
`require('moment/locale/'+lang)`

How can I make sure to get translation from i18N?

**Comment by BrockReece** [comment]
I know that your `require` is dynamic, and that `import` can't handle this... but if you statically import the locale does it work?

```js
import from 'moment/locale/en'
```

I think if you require dynamic imports, I think it is best to carry on using the `require` statement.

**Comment by Alifar** [comment]
> I know that your `require` is dynamic, and that `import` can't handle this... but if you statically import the locale does it work?

No, that doesn't work neither using it like a static import or dynamic require.
