### ISSUE TITLE
Warning on iso8601 string date

### ISSUE THREAD

**Issue by darkiron** [brockpetrie/vue-moment#76]
Hi,
I have a formated date on ISO8601 format: `2018-01-01T00:00:00+01:00`
And have a warning on this string: 

> vue-moment.js:39 Could not build a valid `moment` object from input.

Have a solution  ?

**Comment by BrockReece** [comment]
Hi,

I just tested this out in a sandbox and it appears to work?
https://codesandbox.io/s/9ozoqw832w

Can you build reproduce your issue in a sandbox?

**Comment by darkiron** [comment]
my app code look-like this: 
[![Edit moment error](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/0m9441r3nn)

bu for this time I can't reproduce this issue
