### ISSUE TITLE
[BUG] Weekdays language set only on second render

### ISSUE THREAD

**Issue by iec989** [brockpetrie/vue-moment#77]
`this.$moment().format('MMM')` and `this.$moment().format('dddd')` is showing the text in English during the first render.

During the second render, however, they appear in the locale language.

As a curiosity, when it's in English, the first letter is uppercase, while with the locale is lowercase.

I've tried moving the first render call from `created()` to `mounted()`, but it didn't work.

Any idea of what's going on?

**Comment by BrockReece** [comment]
Does this behave the same if you use raw `moment` instead of using the plugin ie...
```js
moment().format('dddd')
// instead of
this.$moment().format('dddd')
```

**Comment by iec989** [comment]
Sorry guys... I was doing the `this.$moment.locale(globalLocale);` in the mounted instead of created function of the app.js
