### ISSUE TITLE
Does this work with VueJS 2.0/2.5?

### ISSUE THREAD

**Issue by theianjohnson** [brockpetrie/vue-moment#78]
Would love to know what the compatibility is supposed to be?

**Comment by scherii** [comment]
It definitely works with 2.5 and should so with 2.0. 🙂

**Comment by theianjohnson** [comment]
I thought it should, but I've been going in circles trying to get this to work in a child component and I just have no idea what I'm doing wrong...

Do you have any working example I can look at of this being included globally, but the filter being used in a child component?

**Comment by scherii** [comment]
```javascript
import Vue from 'vue'
import moment from 'moment'
import VueMoment from 'vue-moment'

Vue.use(VueMoment, {
	moment
})
```

With this in your `main.js` you can use it in your child components:
```javascript
// this works after 4.0.0 is released
>{{ [timestamp, 'X'] | moment("utc", "dddd, D. MMMM Y → HH:mm")  }}
```
or simply
```javascript
{{ variable | moment("Y") }}
```
