### ISSUE TITLE
Set vue-moment to default always to UTC time

### ISSUE THREAD

**Issue by stratosgear** [brockpetrie/vue-moment#83]
I saw with the latest 4.0.0 release the addition of the utc function.

So I can now do:

```
{{ someDate | moment("utc", "YYYY-MM-DD HH:mm") }}
```

and it works fine.

But I cannot find a way to configure vue-moment  to **always** use UTC.

Is this a limitation of moment or vue-moment or is it just me just not knowing how to default it like this?

**Comment by brockpetrie** [comment]
Currently no plans to allow defaulting to UTC, so the best way to go about this (without forking) would be using Moment Timezone: https://momentjs.com/timezone/docs/#/using-timezones/default-timezone/.

`vue-moment` _should_ respect the default timezone, but I haven't tried it.

**Comment by MaTToX3** [comment]
Hello,

I hope there is no issue re-opening this issue.

Setting up default timezone via moment-timezone works just fine, however it would be great, if I could set a global application setting for automatically converting all dates to specific timezone.

For example, at the moment, I have to first do:
`moment().tz.setDefault('UTC')`
so Vue knows what my timezone is on the server, then I have to manually convert it to my prefered timezone each time I output the date, like so: 
`entry.updated_at | moment('timezone', 'Europe/Ljubljana', 'd.MM.Y HH:mm')`

I would just like to set the "default convert to" globally so I don't have to convert it every time.
