### ISSUE TITLE
Syntax error when transpiling via Babel (version 4.0.0)

### ISSUE THREAD

**Issue by dirknilius** [brockpetrie/vue-moment#86]
When transpiling via Babel you get a `Cannot assign to read only property 'exports' of object '#<Object>'` javascript error. This is because you are mixing ES6 `require` with ES5 `module.export`. This is not allowed. Change `module.export` to `export default` and everything is fine. Since you are using ES6 syntax, you should also add a build setup with transpiling to your project and ship a minified version. This is best practice for JS libs. This version cannot be used in older Browsers like IE. See https://github.com/brockpetrie/vue-moment/issues/85

**Comment by BrockReece** [comment]
@dirknilius thanks for this, I will look into it.
