### ISSUE TITLE
Can we use the moment to component props? 

### ISSUE THREAD

**Issue by doyevaristo** [brockpetrie/vue-moment#89]
For component its easy to use 
`<strong>create_date | moment("calendar")</strong>`
but do we have an option to put moment() to component attributes?

 just like 
`<strong :title="moment(created_date).format('ddd, MMM DD YYYY, h:mm:ss a')">create_date | moment("calendar")</strong>`

**Comment by BrockReece** [comment]
You should be able to use `$moment`

```html
<strong :title="$moment(created_date).format('ddd, MMM DD YYYY, h:mm:ss a')">create_date | moment("calendar")</strong>
```
