### ISSUE TITLE
converting string to date object not working well

### ISSUE THREAD

**Issue by flamner** [brockpetrie/vue-moment#94]
I have string value for ex. "01-07-2018" and vue method:

`formatDate() {
            this.formatted.date = moment(this.date, 'DD-MM-YYYY')
        }`

and it return invalid date object :/

`_d:Fri Jul 13 2018 00:00:00 GMT+0200 (czas środkowoeuropejski letni)
_f:"DD-MM-YYYY"
_i:"13-07-2018"
`
wtf??

**Comment by brockpetrie** [comment]
Hey @flamner, looks like your question is related specifically to moment and not vue-moment. Please refer to their docs and issues.

https://momentjs.com/docs/
https://github.com/moment/moment/issues
