### ISSUE TITLE
How to use with plugins?

### ISSUE THREAD

**Issue by AlbertRAR** [brockpetrie/vue-moment#98]
Hi,
Is it possible to use `vue-moment` with `moment.js` plugins such as [Moment Duration Format](https://github.com/jsmreese/moment-duration-format)? If so, how should we use it?

**Comment by brockpetrie** [comment]
Good question! Usual response is that I haven't tried using this with any moment plugins but I wouldn't have high hopes for interoperability.

Looking at the duration format plugin specifically though, it seems like it might work by having it be a final filter in a chain, like...

```<span>{{ [-10, 'minutes'] | duration('add', 'PT11M') | duration('format', 'h:mm') }}</span>```

...but I can't make any promises. Good luck!
